---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service-expose
  namespace: default
  labels:
    app: neo4j-service
spec:
  ports:
  - name: neo4j-service
    protocol: TCP
    port: 31711
    targetPort: 7474
    nodePort: 31711
  selector:
    app: neo4j-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  labels:
    app: neo4j-service
spec:
  ports:
  - port: 7474
    targetPort: 7474
    name: neo4j-service
  clusterIP: None
  selector:
    app: neo4j-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: neo4j-service
spec:
  serviceName: "neo4j-service"
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-service
  template:
    metadata:
      labels:
        app: neo4j-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: neo4j-service
        image: neo4j:2.3
        ports:
        - containerPort: 7474
        env:
        - name: NEO4J_AUTH
          value: "none"
  podManagementPolicy: "Parallel"